/*
  LISTA DE PRODUCTOS
  ---------------------------------
  Cada producto es un bloque entre { }. Para agregar uno nuevo, copiá un
  bloque completo (desde la { hasta la }, ) y pegalo antes del ] final,
  después cambiá los datos.

  Campos:
    id            -> número único, no repetir (1, 2, 3, ...)
    nombre        -> nombre del perfume
    marca         -> marca del perfume
    tipo          -> "Decant" o "Perfume" (perfume completo)
    genero        -> "Hombre", "Mujer" o "Unisex"
    ml            -> tamaño en mililitros (número, sin la palabra "ml")
    precio        -> precio en números, sin puntos ni comas (ej: 5000)
    imagen        -> nombre del archivo de imagen dentro de images/productos/
                     (si no tenés foto todavía, dejá "placeholder.svg")
    descripcion   -> texto corto sobre el perfume
    destacado     -> true si querés que aparezca primero, si no false
    disponible    -> true si hay stock, false si está agotado
*/

window.PRODUCTOS = [
  {
    id: 1,
    nombre: "Asad Elixir",
    marca: "Lattafa",
    tipo: "Decant",
    genero: "Hombre",
    ml: 5,
    precio: 5440,
    imagen: "asad-elixir.png",
    descripcion: "Eau de Parfum intenso y amaderado, inspirado en la fuerza del león.",
    destacado: true,
    disponible: true,
  },
  {
    id: 2,
    nombre: "Asad Elixir",
    marca: "Lattafa",
    tipo: "Perfume",
    genero: "Hombre",
    ml: 100,
    precio: 40000,
    imagen: "asad-elixir.png",
    descripcion: "Frasco original 100ml.",
    destacado: true,
    disponible: true,
  },
  {
    id: 3,
    nombre: "Mandaryn Sky",
    marca: "Armaf",
    tipo: "Decant",
    genero: "Hombre",
    ml: 5,
    precio: 5260,
    imagen: "mandaryn-sky.png",
    descripcion: "Odyssey Homme Limited Edition, fresco y vibrante.",
    destacado: false,
    disponible: true,
  },
  {
    id: 4,
    nombre: "Mandaryn Sky",
    marca: "Armaf",
    tipo: "Perfume",
    genero: "Hombre",
    ml: 100,
    precio: 50000,
    imagen: "mandaryn-sky.png",
    descripcion: "Frasco original 100ml.",
    destacado: false,
    disponible: true,
  },
  {
    id: 5,
    nombre: "Hawas Ice",
    marca: "Rasasi",
    tipo: "Decant",
    genero: "Hombre",
    ml: 5,
    precio: 5550,
    imagen: "hawas-ice.png",
    descripcion: "Frescura intensa que deja huella.",
    destacado: false,
    disponible: true,
  },
  {
    id: 6,
    nombre: "Hawas Ice",
    marca: "Rasasi",
    tipo: "Perfume",
    genero: "Hombre",
    ml: 100,
    precio: 45000,
    imagen: "hawas-ice.png",
    descripcion: "Frasco original 100ml.",
    destacado: false,
    disponible: true,
  },
  {
    id: 7,
    nombre: "His Confession",
    marca: "Lattafa",
    tipo: "Decant",
    genero: "Hombre",
    ml: 5,
    precio: 5810,
    imagen: "his-confession.png",
    descripcion: "Edición exclusiva, elegante y envolvente.",
    destacado: false,
    disponible: true,
  },
  {
    id: 8,
    nombre: "His Confession",
    marca: "Lattafa",
    tipo: "Perfume",
    genero: "Hombre",
    ml: 100,
    precio: 55000,
    imagen: "his-confession.png",
    descripcion: "Frasco original 100ml.",
    destacado: false,
    disponible: true,
  },
  {
    id: 9,
    nombre: "9 PM Night Out",
    marca: "Afnan",
    tipo: "Decant",
    genero: "Hombre",
    ml: 5,
    precio: 5850,
    imagen: "9pm-night-out.png",
    descripcion: "Una fragancia más allá del tiempo, para noches inolvidables.",
    destacado: false,
    disponible: true,
  },
  {
    id: 10,
    nombre: "9 PM Night Out",
    marca: "Afnan",
    tipo: "Perfume",
    genero: "Hombre",
    ml: 100,
    precio: 50000,
    imagen: "9pm-night-out.png",
    descripcion: "Frasco original 100ml.",
    destacado: false,
    disponible: true,
  },
  {
    id: 11,
    nombre: "Khamrah",
    marca: "Lattafa",
    tipo: "Decant",
    genero: "Hombre",
    ml: 5,
    precio: 5100,
    imagen: "khamrah.png",
    descripcion: "Oriental gourmand, fuerza en cada esencia.",
    destacado: false,
    disponible: true,
  },
  {
    id: 12,
    nombre: "Khamrah",
    marca: "Lattafa",
    tipo: "Perfume",
    genero: "Hombre",
    ml: 100,
    precio: 50000,
    imagen: "khamrah.png",
    descripcion: "Frasco original 100ml.",
    destacado: false,
    disponible: true,
  },
  {
    id: 13,
    nombre: "La Bomba",
    marca: "Carolina Herrera",
    tipo: "Decant",
    genero: "Mujer",
    ml: 5,
    precio: 4787,
    imagen: "la-bomba.png",
    descripcion: "Esencia nórdica, fuerza en cada nota.",
    destacado: false,
    disponible: true,
  },
  {
    id: 14,
    nombre: "La Bomba",
    marca: "Carolina Herrera",
    tipo: "Perfume",
    genero: "Mujer",
    ml: 80,
    precio: 50000,
    imagen: "la-bomba.png",
    descripcion: "Frasco original 80ml.",
    destacado: false,
    disponible: true,
  },
];
